### ISSUE TITLE
Compatibility with io.js

### ISSUE THREAD

**Issue by albertosantini** [TooTallNate/node-time#73]
The module doesn't compile with io.js 2.0.2.

**Comment by arthurschreiber** [comment]
The code in the `master` branch does work fine, it just was not released yet as a new npm package.

You can work around this by running: `npm install git+https://github.com/TooTallNate/node-time.git`

@TooTallNate Can we please have a new tagged release on npm?

**Comment by albertosantini** [comment]
Master tested. It is ok.

A new release will be better. Thanks.

**Comment by TooTallNate** [comment]
v0.11.3 published to npm.
